name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: npm run lint
      - run: npm run test
      # - run: tar -cf dist.tar dist
      # - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
      #   with:
      #     name: app.tar
      #     path: app.tar

  # dev-deploy:
  #   needs:
  #     - build
  #   if: ${{ github.ref != 'refs/heads/main' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

  #     - uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
  #       with:
  #         node-version-file: '.nvmrc'
  #     - run: npm install
  #     - run: npm run lint
  #     - run: npm run build
  #     - run: npm run test
  #     - uses: cloudflare/wrangler-action@2.0.0
  #       with:
  #         apiToken: ${{ secrets.CF_API_TOKEN }}
  #         environment: dev

  deploy:
    name: prod deploy
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - uses: cloudflare/wrangler-action@4c10c1822abba527d820b29e6333e7f5dac2cabd # tag=2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          